#
# requires the following gitlab secret variables
# - DOCKER_REGISTRY_USERNAME    # will be the owner of the uploaded Docker image
# - DOCKER_REGISTRY_PASSWORD    # corresponding password
# - DOCKER_REGISTRY_EMAIL
#

image: maven:3.6.0-jdk-8

before_script:
  - apt-get update && apt-get install -y libxml2-utils
  - export BASELINE=2.0.0-M2
  - export REVISION=$BASELINE.$(date +%Y%m%d)-$(date +%H%M)-$(echo $CI_COMMIT_SHA | cut -c1-8)
  - export METADATA=https://repo.incode.cloud/repository/maven/org/apache/isis/core/isis/maven-metadata.xml
  - export ISIS_VERSION=`curl -s GET $METADATA | xmllint --xpath 'string(//metadata/versioning/latest)' -`
  - printf '#!/bin/sh\necho "=== $FLAVOR ==="\necho "REVISION=$REVISION"\necho "ISIS_VERSION=$ISIS_VERSION"\n' > ./dump_env.sh
  - printf '#!/bin/sh\nmvn install -Dflavor=$FLAVOR -Dskip.git -Dskip.arch -DskipTests -Drevision=$REVISION -Disis.version=$ISIS_VERSION -Dmavenmixin-docker --batch-mode\n' > ./build.sh
  - printf '#!/bin/sh\nmvn -s .m2/settings.xml docker:push@push-image-latest -Drevision=$REVISION -Disis.version=$ISIS_VERSION -DskipTests -DskipTag -Dskip.isis-swagger -Dmavenmixin-docker -Ddocker-plugin.serverId=docker-registry\n' > ./push_latest.sh
  - printf '#!/bin/sh\nmvn -s .m2/settings.xml docker:push@push-image-tagged -Dflavor=$FLAVOR -Drevision=$REVISION -Disis.version=$ISIS_VERSION -DskipTests -Dskip.isis-swagger -Dmavenmixin-docker -Ddocker-plugin.serverId=docker-registry\n' > ./push_flavor.sh

services:
  - docker:dind

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  APP_NAME: isis-2-demo

stages:
  - tomcat
#  - payara

job tomcat:
  stage: tomcat
  script:
    - export FLAVOR=tomcat
    - sh dump_env.sh
    - cat build.sh
    - sh build.sh
    - cat push_latest.sh
    - sh push_latest.sh
    - cat push_flavor.sh
    - sh push_flavor.sh

job payara:
  stage: payara
  script:
    - export FLAVOR=payara
    - sh dump_env.sh
    - sh build.sh
    - sh push_flavor.sh
