#
# requires the following gitlab secret variables
#
# - NEXUS_USERNAME
# - NEXUS_PASSWORD
# - NEXUS_REPO_URL
# - DOCKER_REGISTRY_USERNAME
# - DOCKER_REGISTRY_PASSWORD
# - DOCKER_REGISTRY_EMAIL
#
#

image: maven:3.5.3-jdk-8

before_script:
  - export BASELINE=2.0.0-M1
  - export REVISION=$BASELINE.$(date +%Y%m%d)-$(date +%H%M)-$(echo $CI_COMMIT_SHA | cut -c1-7)

services:
  - docker:dind

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  MAVEN_CLI_OPTS: "--batch-mode"
  DOCKER_REGISTRY_ID: "docker-hub"
  DOCKER_REGISTRY_URL: "https://index.docker.io/v1/"
  DOCKER_REGISTRY_REPOSITORY: "simpleapp"

stages:
  - build-package

build-package:
  stage: build-package
  script:
    - echo "REVISION=$REVISION"
    - cd core
    - >
      mvn $MAVEN_CLI_OPTS \
          -s .m2/settings.xml \
          clean deploy \
          -Drevision=$REVISION \
          -Dnexus-deploy \
          -Dnexus-deploy.repositoryUrl=$NEXUS_REPO_URL \
          $CORE_ADDITIONAL_OPTS
    - cd ..
    - cd example/application/simpleapp
    - >
      mvn $MAVEN_CLI_OPTS \
          install \
          -Drevision=$REVISION \
          -Disis.version=$REVISION \
          -Dmavenmixin-docker \
          -Ddocker-plugin.imageName=$DOCKER_REGISTRY_USERNAME/$DOCKER_REGISTRY_REPOSITORY
    - >
      mvn $MAVEN_CLI_OPTS \
          -s .m2/settings.xml \
          docker:push@push-image-tagged \
          -pl webapp \
          -Drevision=$REVISION \
          -Disis.version=$REVISION \
          -DskipTests \
          -Dskip.isis-swagger \
          -Dmavenmixin-docker \
          -Ddocker-plugin.imageName=$DOCKER_REGISTRY_USERNAME/$DOCKER_REGISTRY_REPOSITORY \
          -Ddocker-plugin.serverId=$DOCKER_REGISTRY_ID \
          -Ddocker.registryUrl=$DOCKER_REGISTRY_URL
    - cd ../../..


