stages:
  - build

maven-build:
  image: maven:3-jdk-8
  stage: build
  script: "mvn clean install -B -Dskip.arch -D revision=2.0.0-M1.$(date +%Y%m%d)-$(git rev-parse --short HEAD) && \
          cd example/application/simpleapp && \
          mvn install -B Dmavenmixin-docker -D revision=2.0.0-M1.$(date +%Y%m%d)-$(git rev-parse --short HEAD) "

