image: maven:3.6.2-jdk-11

stages:
  - build-package-push

variables:
  BASELINE: 2.0.0-M2
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  ORG_NAME: "apacheisis"
  
include:
  - local: scripts/ci/core-gitlab-ci.yml

before_script:
  - export PROJECT_ROOT_DIR=$CI_PROJECT_DIR
  - export CI_SCRIPTS_DIR=$PROJECT_ROOT_DIR/scripts/ci
  - export REVISION=$BASELINE.$(date +%Y%m%d)-$(date +%H%M)-$(echo $CI_COMMIT_SHA | cut -c1-8)
