image: maven:3.5.3-jdk-8

before_script:
  - export BASELINE=2.0.0-M1
  - export REVISION=$BASELINE.$(date +%Y%m%d)-$(date +%H%M)-$(echo $CI_COMMIT_SHA | cut -c1-7)

services:
  - docker:dind

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  MAVEN_CLI_OPTS: "--batch-mode"

stages:
  - build-package

build-package:
  stage: build-package
  script:
    - echo "REVISION=$REVISION"
    - cd core
    - >
      mvn $MAVEN_CLI_OPTS \
          clean install \
          -Drevision=$REVISION
    - cd ..
    - cd example/application/simpleapp
    - >
      mvn $MAVEN_CLI_OPTS \
          install \
          -Drevision=$REVISION \
          -Disis.version=$REVISION \
          -Dmavenmixin-docker \
          -Ddocker-plugin.imageName=isis/simpleapp
    - cd ../../..


