#
# requires the following gitlab secret variables
#
# - DOCKER_REGISTRY_USERNAME
# - DOCKER_REGISTRY_PASSWORD
# - DOCKER_REGISTRY_EMAIL
#
#

image: maven:3.5.3-jdk-8

before_script:
  - export BASELINE=2.0.0-M1
  - export REVISION=$BASELINE.$(date +%Y%m%d)-$(git rev-parse --short HEAD)

services:
  - docker:dind

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository -Dskip.cloudbees-estatio-repositories -Dskip.sonatype-snapshots -Dskip.apache-snapshots"
  DOCKER_REGISTRY_ID: "docker-hub"
  DOCKER_REGISTRY_URL: "https://index.docker.io/v1/"
  DOCKER_REGISTRY_REPOSITORY: "simpleapp"

stages:
  - build-package

build-package:
  stage: build-package
  script:
    - echo "REVISION=$REVISION"
    - cd core
    - >
      mvn --batch-mode \
          clean install \
          -Drevision=$REVISION
    - cd ..
    - cd example/application/simpleapp
    - >
      mvn -s .m2/settings.xml \
          --batch-mode \
          install \
          -Drevision=$REVISION \
          -Disis.version=$REVISION \
          -Dmavenmixin-docker \
          -Ddocker-plugin.imageName=$DOCKER_REGISTRY_USERNAME/$DOCKER_REGISTRY_REPOSITORY
    - >
      mvn -s .m2/settings.xml \
          --batch-mode \
          docker:push@push-image-tagged \
          -pl webapp \
          -Drevision=$REVISION \
          -Disis.version=$REVISION \
          -DskipTests \
          -Dskip.isis-swagger \
          -Dmavenmixin-docker \
          -Ddocker-plugin.imageName=$DOCKER_REGISTRY_USERNAME/$DOCKER_REGISTRY_REPOSITORY \
          -Ddocker-plugin.serverId=$DOCKER_REGISTRY_ID \
          -Ddocker.registryUrl=$DOCKER_REGISTRY_URL
    - cd ../../..


