name: Build Site

on: [push]

jobs:
  build:
    name: build-local-no-push
    runs-on: ubuntu-latest
    env:
      # to be shared amoung all steps of this job ...
      
      PROJECT_ROOT_PATH: ${{ github.workspace }}
      CI_SCRIPTS_PATH: ${{ github.workspace }}/scripts/ci
      
      # not used 
      TIMESTAMP: ${{ github.event.head_commit.timestamp }}
      
    steps:
    - uses: actions/checkout@v1
    
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    
    - name: Print Maven Version
      run: mvn --version
    
    - name: Setup Script Environment
      shell: bash
      # we write the more tricky varibles to the $SHARED_VARS_FILE using the full power of bash commands
      # then we simply print all the (non-secret) variables as used by the build scripts to the console
      run: |
        echo ==============  ENV  =================
        echo TIMESTAMP\: $TIMESTAMP
        echo PROJECT_ROOT_PATH\: $PROJECT_ROOT_PATH
        echo CI_SCRIPTS_PATH\: $CI_SCRIPTS_PATH
        echo ======================================
    
    ## now prepare then build the site (antora build) ...
    
    - name: Print Node Version
      run: node --version
    
    - name: Install NVM
      shell: bash
      run: bash $CI_SCRIPTS_PATH/install-nvm.sh
      
    - name: Install Antora
      shell: bash
      working-directory: ${{ env.PROJECT_ROOT_PATH }}
      # we install the 'node' modules into the project root under 'node_modules', 
      # because we have no privileges to install them globally with -g option
      run: npm i @antora/cli@2.2 @antora/site-generator-default@2.2 asciidoctor-plantuml@1.3.1
      
    - name: Print Antora Version
      shell: bash
      working-directory: ${{ env.PROJECT_ROOT_PATH }}
      run: $(npm bin)/antora version
    
    - name: Build Site
      shell: bash
      working-directory: ${{ env.PROJECT_ROOT_PATH }}
      run: bash $CI_SCRIPTS_PATH/build-site.sh site.yml
 
# FOR DEBUG USE
#   - name: Dump GitHub context 
#     env:
#       ENV_CONTEXT: ${{ toJson(env) }}
#     run: echo "$ENV_CONTEXT"
#   - name: Dump GitHub context 
#     env:
#       GITHUB_CONTEXT: ${{ toJson(github) }}
#     run: echo "$GITHUB_CONTEXT"
#   - name: Dump job context
#     env:
#       JOB_CONTEXT: ${{ toJson(job) }}
#     run: echo "$JOB_CONTEXT"
#   - name: Dump steps context
#     env:
#       STEPS_CONTEXT: ${{ toJson(steps) }}
#     run: echo "$STEPS_CONTEXT"
#   - name: Dump runner context
#     env:
#       RUNNER_CONTEXT: ${{ toJson(runner) }}
#     run: echo "$RUNNER_CONTEXT"
#   - name: Dump strategy context
#     env:
#       STRATEGY_CONTEXT: ${{ toJson(strategy) }}
#     run: echo "$STRATEGY_CONTEXT"
#   - name: Dump matrix context
#     env:
#       MATRIX_CONTEXT: ${{ toJson(matrix) }}
#     run: echo "$MATRIX_CONTEXT"
           
           